'use strict';

Object.defineProperty(exports, "__esModule", {
  value: true
});
var eventEnum = {
  PCF_VALIDATION_SUCCESS: 'PCF.VALIDATION.SUCCESS',
  PCF_FETCH_SUCCESS: 'PCF.FETCH.SUCCESS',
  PUBLISHING_VALIDATION_START: 'PUBLISHING.VALIDATION.START',
  PUBLISHING_VALIDATION_END: 'PUBLISHING.VALIDATION.END',
  PUBLISHING_PUBLISH_END: 'PUBLISHING.PUBLISH.END'
};

exports.default = eventEnum;